---
- name: Install prereqisites
  gather_facts: no
  hosts: all
  roles:
    - role: prereqisites
      java_name: java-1.8.0-openjdk
      pre_dns: false

- name: Install Cassandra cluster
  hosts: cassandra
  roles:
    - role: cassandra
      cassandra_cluster_name: janus_cluster

- name: Install Elasticsearch master-host
  gather_facts: no
  hosts: elastic_master
  roles:
    - role: elasticsearch
      es_data_dirs: 
        - "/opt/elasticsearch"
      es_log_dir: "/opt/elasticsearch/logs"
      es_heap_size: "512m"
      es_config:
        cluster.name: "janus_cluster"
        network.host: 0.0.0.0
        cluster.initial_master_nodes: "{{ groups['elastic_master'] | map('extract', hostvars, ['inventory_hostname']) | join(',') }}"
        discovery.seed_hosts: "{{ groups['elastic_master'] | map('extract', hostvars, ['inventory_hostname']) | join(':9300,') }}:9300"
        http.port: 9200
        node.data: false
        node.master: true
        node.name: "{{ inventory_hostname }}"
        bootstrap.memory_lock: true
      es_plugin:
        - plugin: ingest-attachment

- name: Install Elasticsearch data-hosts
  gather_facts: no
  hosts: elastic_data
  roles:
    - role: elasticsearch
      es_data_dirs:: "/opt/elasticsearch"
      es_log_dir: "/opt/elasticsearch/logs"
      es_heap_size: "512m"
      es_config:
        cluster.name: "janus_cluster"
        network.host: 0.0.0.0
        cluster.initial_master_nodes: "{{ groups['elastic_master'] | map('extract', hostvars, ['inventory_hostname']) | join(',') }}"
        discovery.seed_hosts: "{{ groups['elastic_master'] | map('extract', hostvars, ['inventory_hostname']) | join(':9300,') }}:9300"
        http.port: 9200
        node.data: true
        node.master: false
        node.name: "{{ inventory_hostname }}"
        bootstrap.memory_lock: true
        indices.recovery.max_bytes_per_sec: 100mb
      es_plugin:
        - plugin: ingest-attachment
      
- name: Install JanusGraph
  gather_facts: no
  hosts: janusgraph
  roles:
    - role: janusgraph
      environment_name: "janus_env"
