---

- name: Install Java and other packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ req_packages }}"

- name: "Update /etc/hosts"
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[item].ansible_host }} {{ hostvars[item].inventory_hostname }}"
    state: present
  loop: "{{ ansible_play_batch }}"
  when: not pre_dns
